### PR TITLE
Explicit port reuse in net.serve

### LINKED ISSUE #127: net: Properly handle ports on HTTP server
Right now, the HTTP server attempts to open on a port and does not error if it fails. This error should be added while still allowing for explicit port reuse for platforms that support it (Linux with SO_REUSEPORT).

### PR DESCRIPTION
**Pull request by Nicell**
Closes #127

### CODE REVIEW

File: net/src/net.cpp [hunk 1]
```diff
@@ -526,6 +531,13 @@ int lua_serve(lua_State* L)
         }
         lua_pop(L, 1);
 
+        lua_getfield(L, 1, "reuseport");
```
Comment (Nicell) [inline net/src/net.cpp:534]: open to a different name for this field

Comment (aatxe) [reply net/src/net.cpp:534]: seems fine to me

**Review by aatxe — APPROVED** [review]
