### PR TITLE
Fix net.serve not being yieldable

### LINKED ISSUE #169: net.serve should allow yielding

### PR DESCRIPTION
**Pull request by ffrostfall**
Fixes #169 by deriving a lua_State from the runtime global lua_State, and then resuming it with the handler function.

### CODE REVIEW

File: net/src/net.cpp [hunk 1]
```diff
@@ -279,7 +279,8 @@ static void processRequest(
     lua_pushvalue(L, -2);
     lua_remove(L, -3);
 
-    if (lua_pcall(L, 1, 1, 0) != 0)
+    int status = lua_resume(L, nullptr, 1);
+    if ((status != LUA_OK) && (status != LUA_YIELD))
```
Comment (aatxe) [inline net/src/net.cpp]:
```suggestion
    if (status != LUA_OK && status != LUA_YIELD)
```

**Review by aatxe — COMMENTED** [review]
Looks good besides a small style nit.

**Review by aatxe — APPROVED** [review]
