### PR TITLE
Fixes the task.spawn, task.defer, and task.resume methods

### LINKED ISSUE #522: Result of `task.spawn` cannot be used with `coroutine.status`
The return value of `task.spawn` doesn't actually seem to return a `thread`. At least not in a way that `coroutine.status` recognizes. 

When attempting to pass the thread in, `coroutine.status` errors with `invalid argument #1 to 'status' (thread expected, got function)`

Minimal repro:

```luau
-- scripts/repro.luau
local task = require("@lute/task")

local thread = task.spawn(function()
	print("do something for a while")
	task.wait(2)
	print("done")
end)

local status = coroutine.status(thread)

print(status)
```

And here's the output:

```
➜  flipbook git:(main) ✗ lute --version         
0.1.0-nightly.20251104
➜  flipbook git:(main) ✗ lute scripts/repro.luau
do something for a while
./scripts/repro.luau:9: invalid argument #1 to 'status' (thread expected, got function)
stacktrace:
[C] function status
./scripts/repro.luau:9
done
```

### PR DESCRIPTION
**Pull request by Vighnesh-V**
Resolves #522 

This PR refactors `task.spawn, defer, resume` to share most of their logic for creating the stack and handing control off to newly created threads. The cause of the bug in #522 was that the stack didn't get set up correctly in the parent stack due to `lua_xmove` popping from the top, so the value that got returned was not callable with `coroutine.status` (because it wasn't a thread). The code I've added documents the invariant that I wanted to maintain along with helpers for correctly setting up the stack.

I've added tests for the following cases:
{task.defer, task.spawn, task.resume } called with { thread | function (except for task.resume, which only takes a thread passed { 0 arguments to resume with, > 0 arguments to resume with }.

I also introduced 'deferSelf' for the argumentless version of task.defer that says to immediately yield the current thread.

### CODE REVIEW

File: lute/task/src/task.cpp [hunk 1]
```diff
@@ -88,14 +91,134 @@ static void yieldLuaStateFor(lua_State* L, uint64_t milliseconds, bool putDeltaT
...
+        // [function, args...]
+        // or
+        // [thread, args...]
+
+        // If passed a thread, we push the 0 or more arguments onto that threads stack and resume it.
+        // If passed a function, we push the function and the 0 or more arguments onto a newly created thread's stack
+        int toPush = lua_gettop(parent);
+        // We only want to resume with the actual number of arguments here, regardless of if the first argument is a thread or a function
+        int numResumeArgs = toPush > 1 ? toPush - 1 : 0;
+        if (!lua_checkstack(L, 1))
```
Comment (annieetang) [inline lute/task/src/task.cpp]: should this checkstack be for `parent`

File: lute/task/src/task.cpp [hunk 2]
```diff
@@ -88,14 +91,134 @@ static void yieldLuaStateFor(lua_State* L, uint64_t milliseconds, bool putDeltaT
...
+            return 1;
+        }
+
+        int resumeStatus = lua_resume(child, parent, resumeArgs);
+        bool ok = resumeStatus == LUA_OK || resumeStatus == LUA_YIELD || resumeStatus == LUA_BREAK;
+
+        if (!ok)
+        {
+            runtime->reportError(child);
+            return 1;
```
Comment (annieetang) [inline lute/task/src/task.cpp:166]:
```suggestion

```
since we error, (and also `return 1` later anyways)

File: tests/lute/task.test.luau [hunk 3]
```diff
@@ -22,4 +22,119 @@ test.suite("LuteTaskSuite", function(suite)
...
+		local thread = task.spawn(function()
+			task.wait(2)
+		end)
+
+		local status = coroutine.status(thread)
+		assert.eq(status, "suspended")
+		coroutine.close(thread)
+	end)
+
+	-- task.spawn with thread, 0 args
```
Comment (annieetang) [inline tests/lute/task.test.luau:48]: is it possible to call `task.spawn()` / what happens if that happens?

**Review by annieetang — COMMENTED** [review]
thx for fixing these!

File: tests/lute/task.test.luau (hunk 3 above)
Comment (Vighnesh-V) [reply tests/lute/task.test.luau:48]: The logic for constructing a thread expects the first thing on the stack to be either a thread or a function. If it's neither, an error is raised with the following message:
```
"Expected a thread or function as the first argument."
```
which models the type of the functions in the typedefs (you have to pass a thread / function)

File: lute/task/src/task.cpp (hunk 1 above)
Comment (Vighnesh-V) [reply lute/task/src/task.cpp]: L and parent are identical here, so this ends up working. I've switched this to parent!

File: lute/task/src/task.cpp (hunk 2 above)
Comment (Vighnesh-V) [reply lute/task/src/task.cpp:166]: runtime->reportError doesn't actually throw an error - it just prints to stderr. That being said, the fallthrough is alright here.

File: tests/lute/task.test.luau (hunk 3 above)
Comment (annieetang) [reply tests/lute/task.test.luau:48]: sounds good! do we want to add a test case showing this or nah

File: lute/task/src/task.cpp [hunk 4]
```diff
@@ -88,14 +91,134 @@ static void yieldLuaStateFor(lua_State* L, uint64_t milliseconds, bool putDeltaT
...
+        }
+
+        int resumeStatus = lua_resume(child, parent, resumeArgs);
+        bool ok = resumeStatus == LUA_OK || resumeStatus == LUA_YIELD || resumeStatus == LUA_BREAK;
+
+        if (!ok)
+        {
+            runtime->reportError(child);
+	    return 1;
```
Comment (annieetang) [inline lute/task/src/task.cpp]:
```suggestion

```

Comment (annieetang) [reply lute/task/src/task.cpp]: or leave but add an indent for formatting?

**Review by annieetang — COMMENTED** [review]
last thing- do we want to specify the error messages a bit more?

`luaL_error(L, "Expected a thread as the first argument.");` -> `luaL_error(L, "Lute resume: Expected a thread as the first argument.");` or something specific? 

since some of the error messages specify which function the error is coming from (e.g., `luaL_error(L, "task.deferSelf does not take any arguments");`

File: lute/task/src/task.cpp (hunk 4 above)
Comment (Vighnesh-V) [reply lute/task/src/task.cpp]: I'll fix the formatting :)

**Comment by Vighnesh-V** [comment]
~~I think inside of `LuauThread` it's fine to just warn with `expected first argument to be thread`.~~

Edit: I've updated LuaThread to take a caller parameter, so we can provide slightly better error messages.

**Review by annieetang — APPROVED** [review]
thanks!!
